<?php

use Illuminate\Database\Seeder;

class ComCodeTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('com_code')->delete();
        
        \DB::table('com_code')->insert(array (
            0 => 
            array (
                'com_cd' => 'ASAL_BANTUAN_1',
                'code_nm' => 'Pemerintah Daerah',
                'code_group' => 'ASAL_BANTUAN',
                'code_value' => 'Pemerintah Daerah',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'com_cd' => 'ASAL_BANTUAN_2',
                'code_nm' => 'Pemerintah Desa',
                'code_group' => 'ASAL_BANTUAN',
                'code_value' => 'Pemerintah Desa',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'com_cd' => 'ASAL_BANTUAN_3',
                'code_nm' => 'Instansi-Organisasi Amal',
                'code_group' => 'ASAL_BANTUAN',
                'code_value' => 'Instansi-Organisasi Amal',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'com_cd' => 'ASAL_BANTUAN_4',
                'code_nm' => 'Teman-Keluarga-Tetangga',
                'code_group' => 'ASAL_BANTUAN',
                'code_value' => 'Teman-Keluarga-Tetangga',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'com_cd' => 'ASAL_BANTUAN_5',
                'code_nm' => 'Lainnya',
                'code_group' => 'ASAL_BANTUAN',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'com_cd' => 'JENIS_BANTUAN_1',
            'code_nm' => 'Sembako/Materi (uang)',
                'code_group' => 'JENIS_BANTUAN',
            'code_value' => 'Sembako/Materi (uang)',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'com_cd' => 'JENIS_BANTUAN_2',
            'code_nm' => 'Logistik Kesehatan (Masker,Obat,dsb)',
                'code_group' => 'JENIS_BANTUAN',
            'code_value' => 'Logistik Kesehatan (Masker,Obat,dsb)',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'com_cd' => 'JENIS_BANTUAN_3',
            'code_nm' => 'Tenaga (Bantuan untuk Lansia/Masyarakat Rentan)',
                'code_group' => 'JENIS_BANTUAN',
            'code_value' => 'Tenaga (Bantuan untuk Lansia/Masyarakat Rentan)',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'com_cd' => 'JENIS_PEKERJAAN_1',
                'code_nm' => 'Pekerja Kantoran',
                'code_group' => 'JENIS_PEKERJAAN',
                'code_value' => 'Pekerja Kantoran',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'com_cd' => 'JENIS_PEKERJAAN_2',
                'code_nm' => 'Buruh Pabrik',
                'code_group' => 'JENIS_PEKERJAAN',
                'code_value' => 'Buruh Pabrik',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'com_cd' => 'JENIS_PEKERJAAN_3',
                'code_nm' => 'Petani',
                'code_group' => 'JENIS_PEKERJAAN',
                'code_value' => 'Petani',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'com_cd' => 'JENIS_PEKERJAAN_4',
                'code_nm' => 'Ibu Rumah Tangga',
                'code_group' => 'JENIS_PEKERJAAN',
                'code_value' => 'Ibu Rumah Tangga',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'com_cd' => 'JENIS_PEKERJAAN_5',
                'code_nm' => 'Tidak Bekerja',
                'code_group' => 'JENIS_PEKERJAAN',
                'code_value' => 'Tidak Bekerja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'com_cd' => 'JENIS_PEKERJAAN_6',
                'code_nm' => 'Lainnya',
                'code_group' => 'JENIS_PEKERJAAN',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_1',
                'code_nm' => 'Rajin Mencuci Tangga',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => 'Rajin Mencuci Tangga',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_2',
            'code_nm' => 'Membatasi Kontak Fisik (Peluk, Cium, Salam)',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
            'code_value' => 'Membatasi Kontak Fisik (Peluk, Cium, Salam)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_3',
                'code_nm' => 'Mengurangi kegiatan sosialisasi',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => 'Mengurangi kegiatan sosialisasi',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_4',
                'code_nm' => 'Memakai Masker',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => 'Memakai Masker',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_5',
                'code_nm' => 'Langsung Mencuci pakaian sehabis bepergian',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => 'Langsung Mencuci pakaian sehabis bepergian',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_6',
                'code_nm' => 'Makan-makanan sehat dan pola makanan teratur',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => 'Makan-makanan sehat dan pola makanan teratur',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_7',
                'code_nm' => 'Memakai disinfektan ke perangkat rumah tangga',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => 'Memakai disinfektan ke perangkat rumah tangga',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'com_cd' => 'KEBIASAAN_DITERAPKAN_8',
                'code_nm' => 'Lainnya',
                'code_group' => 'KEBIASAAN_DITERAPKAN',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_1',
            'code_nm' => 'Kegiatan Rumah Tangga (Menyapu, Mengepel, Mencuci)',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
            'code_value' => 'Kegiatan Rumah Tangga (Menyapu, Mengepel, Mencuci)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_2',
            'code_nm' => 'Bersantai (Di Rumah)',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
            'code_value' => 'Bersantai (Di Rumah)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_3',
            'code_nm' => 'Kegiatan Sosialisasi (Arisan, Berkumpul dengan teman, Tirakatan, Pengajian)',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
            'code_value' => 'Kegiatan Sosialisasi (Arisan, Berkumpul dengan teman, Tirakatan, Pengajian)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_4',
            'code_nm' => 'Rekreasi (Berjalan-jalan keluar rumah)',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
            'code_value' => 'Rekreasi (Berjalan-jalan keluar rumah)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_5',
            'code_nm' => 'Bermain (dengan teman sebaya)',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
            'code_value' => 'Bermain (dengan teman sebaya)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_6',
            'code_nm' => 'Tidak ada kegiatan khusus yang dilakukan (Berisirahat)',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
            'code_value' => 'Tidak ada kegiatan khusus yang dilakukan (Berisirahat)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'com_cd' => 'KEGIATAN_SEHARI_HARI_7',
                'code_nm' => 'Lainnya',
                'code_group' => 'KEGIATAN_SEHARI_HARI',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'com_cd' => 'KEMAMPUAN_1',
                'code_nm' => 'Sangat Tidak Baik',
                'code_group' => 'KEMAMPUAN',
                'code_value' => 'Sangat Tidak Baik',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'com_cd' => 'KEMAMPUAN_2',
                'code_nm' => 'Kurang Baik',
                'code_group' => 'KEMAMPUAN',
                'code_value' => 'Kurang Baik',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'com_cd' => 'KEMAMPUAN_3',
                'code_nm' => 'Cukup Baik',
                'code_group' => 'KEMAMPUAN',
                'code_value' => 'Cukup Baik',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'com_cd' => 'KEMAMPUAN_4',
                'code_nm' => 'Baik',
                'code_group' => 'KEMAMPUAN',
                'code_value' => 'Baik',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'com_cd' => 'KEMAMPUAN_5',
                'code_nm' => 'Sangat Baik',
                'code_group' => 'KEMAMPUAN',
                'code_value' => 'Sangat Baik',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'com_cd' => 'KEMUDAHAN_1',
                'code_nm' => 'Sangat Sulit',
                'code_group' => 'KEMUDAHAN',
                'code_value' => 'Sangat Sulit',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'com_cd' => 'KEMUDAHAN_2',
                'code_nm' => 'Cukup Sulit',
                'code_group' => 'KEMUDAHAN',
                'code_value' => 'Cukup Sulit',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'com_cd' => 'KEMUDAHAN_3',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'KEMUDAHAN',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'com_cd' => 'KEMUDAHAN_4',
                'code_nm' => 'Cukup Mudah',
                'code_group' => 'KEMUDAHAN',
                'code_value' => 'Cukup Mudah',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'com_cd' => 'KEMUDAHAN_5',
                'code_nm' => 'Sangat Mudah',
                'code_group' => 'KEMUDAHAN',
                'code_value' => 'Sangat Mudah',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'com_cd' => 'KEPEDULIAN_1',
                'code_nm' => 'Tidak Peduli',
                'code_group' => 'KEPEDULIAN',
                'code_value' => 'Tidak Peduli',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'com_cd' => 'KEPEDULIAN_2',
                'code_nm' => 'Ingin Mengetahui Lebih Lanjut',
                'code_group' => 'KEPEDULIAN',
                'code_value' => 'Ingin Mengetahui Lebih Lanjut',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'com_cd' => 'KEPEDULIAN_3',
                'code_nm' => 'Bisa jadi Percaya',
                'code_group' => 'KEPEDULIAN',
                'code_value' => 'Bisa jadi Percaya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'com_cd' => 'KEPEDULIAN_4',
                'code_nm' => 'Sangat Tidak Percaya',
                'code_group' => 'KEPEDULIAN',
                'code_value' => 'Sangat Tidak Percaya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'com_cd' => 'KEPERCAYAAN_1',
                'code_nm' => 'Tidak Percaya',
                'code_group' => 'KEPERCAYAAN',
                'code_value' => 'Tidak Percaya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'com_cd' => 'KEPERCAYAAN_2',
                'code_nm' => 'Ragu-ragu',
                'code_group' => 'KEPERCAYAAN',
                'code_value' => 'Ragu-ragu',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'com_cd' => 'KEPERCAYAAN_3',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'KEPERCAYAAN',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'com_cd' => 'KEPERCAYAAN_4',
                'code_nm' => 'Sangat Percaya',
                'code_group' => 'KEPERCAYAAN',
                'code_value' => 'Sangat Percaya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'com_cd' => 'KEPERCAYAAN_5',
                'code_nm' => 'Tetap Waspada',
                'code_group' => 'KEPERCAYAAN',
                'code_value' => 'Tetap Waspada',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'com_cd' => 'KESEJAHTERAAN_1',
                'code_nm' => 'Sangat Tidak Sejahtera',
                'code_group' => 'KESEJAHTERAAN',
                'code_value' => 'Sangat Tidak Sejahtera',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'com_cd' => 'KESEJAHTERAAN_2',
                'code_nm' => 'Tidak Terlalu Sejahtera',
                'code_group' => 'KESEJAHTERAAN',
                'code_value' => 'Tidak Terlalu Sejahtera',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'com_cd' => 'KESEJAHTERAAN_3',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'KESEJAHTERAAN',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'com_cd' => 'KESEJAHTERAAN_4',
                'code_nm' => 'Cukup Sejahtera',
                'code_group' => 'KESEJAHTERAAN',
                'code_value' => 'Cukup Sejahtera',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'com_cd' => 'KESEJAHTERAAN_5',
                'code_nm' => 'Sangat Sejahtera',
                'code_group' => 'KESEJAHTERAAN',
                'code_value' => 'Sangat Sejahtera',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'com_cd' => 'MEDIS_1',
                'code_nm' => 'Suplemen-Vitamin',
                'code_group' => 'MEDIS',
                'code_value' => 'Suplemen-Vitamin',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'com_cd' => 'MEDIS_2',
            'code_nm' => 'Obat Penyakit Khusus (Diabetes, Sakit Jantung, dsb)',
                'code_group' => 'MEDIS',
            'code_value' => 'Obat Penyakit Khusus (Diabetes, Sakit Jantung, dsb)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'com_cd' => 'MEDIS_3',
                'code_nm' => 'Masker',
                'code_group' => 'MEDIS',
                'code_value' => 'Masker',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'com_cd' => 'MEDIS_4',
                'code_nm' => 'Handsanitizer',
                'code_group' => 'MEDIS',
                'code_value' => 'Handsanitizer',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'com_cd' => 'MEDIS_5',
                'code_nm' => 'Disinfektan',
                'code_group' => 'MEDIS',
                'code_value' => 'Disinfektan',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'com_cd' => 'MEDIS_6',
            'code_nm' => 'Obat Penyakit Ringan (Flu, Demam, Batuk, dsb)',
                'code_group' => 'MEDIS',
            'code_value' => 'Obat Penyakit Ringan (Flu, Demam, Batuk, dsb)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'com_cd' => 'MEDIS_7',
                'code_nm' => 'Sabun',
                'code_group' => 'MEDIS',
                'code_value' => 'Sabun',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'com_cd' => 'MEDIS_8',
                'code_nm' => 'Lainnya',
                'code_group' => 'MEDIS',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'com_cd' => 'PEMAHAMAN_1',
                'code_nm' => 'Sangat Tidak Mengerti',
                'code_group' => 'PEMAHAMAN',
                'code_value' => 'Sangat Tidak Mengerti',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'com_cd' => 'PEMAHAMAN_2',
                'code_nm' => 'Tidak Terlalu Mengerti',
                'code_group' => 'PEMAHAMAN',
                'code_value' => 'Tidak Terlalu Mengerti',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'com_cd' => 'PEMAHAMAN_3',
                'code_nm' => 'Cukup Mengerti',
                'code_group' => 'PEMAHAMAN',
                'code_value' => 'Cukup Mengerti',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'com_cd' => 'PEMAHAMAN_4',
                'code_nm' => 'Mengerti',
                'code_group' => 'PEMAHAMAN',
                'code_value' => 'Mengerti',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'com_cd' => 'PEMAHAMAN_5',
                'code_nm' => 'Sangat Mengerti',
                'code_group' => 'PEMAHAMAN',
                'code_value' => 'Sangat Mengerti',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'com_cd' => 'PEMENUHAN_KEBUTUHAN_1',
                'code_nm' => 'Tidak Mendapat Bantuan',
                'code_group' => 'PEMENUHAN_KEBUTUHAN',
                'code_value' => 'Tidak Mendapat Bantuan',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'com_cd' => 'PEMENUHAN_KEBUTUHAN_2',
                'code_nm' => 'Cukup',
                'code_group' => 'PEMENUHAN_KEBUTUHAN',
                'code_value' => 'Cukup',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'com_cd' => 'PEMENUHAN_KEBUTUHAN_3',
                'code_nm' => 'Kurang',
                'code_group' => 'PEMENUHAN_KEBUTUHAN',
                'code_value' => 'Kurang',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'com_cd' => 'PEMENUHAN_KEBUTUHAN_4',
                'code_nm' => 'Berlebih',
                'code_group' => 'PEMENUHAN_KEBUTUHAN',
                'code_value' => 'Berlebih',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'com_cd' => 'PENGARUH_1',
            'code_nm' => 'Biasa Saja(Tidak Terpengaruh)',
                'code_group' => 'PENGARUH',
            'code_value' => 'Biasa Saja(Tidak Terpengaruh)',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'com_cd' => 'PENGARUH_2',
                'code_nm' => 'Tidak Peduli',
                'code_group' => 'PENGARUH',
                'code_value' => 'Tidak Peduli',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'com_cd' => 'PENGARUH_3',
                'code_nm' => 'Menjadi Kritis dalam memilah informasi',
                'code_group' => 'PENGARUH',
                'code_value' => 'Menjadi Kritis dalam memilah informasi',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'com_cd' => 'PENGARUH_4',
                'code_nm' => 'Saya Tidak akan percaya apapun lagi',
                'code_group' => 'PENGARUH',
                'code_value' => 'Saya Tidak akan percaya apapun lagi',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'com_cd' => 'PENGHASILAN_1',
                'code_nm' => 'Tidak Berpenghasilan',
                'code_group' => 'PENGHASILAN',
                'code_value' => 'Tidak Berpenghasilan',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'com_cd' => 'PENGHASILAN_2',
                'code_nm' => '100.000-300.000',
                'code_group' => 'PENGHASILAN',
                'code_value' => '100.000-300.000',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'com_cd' => 'PENGHASILAN_3',
                'code_nm' => '300.000-500.000',
                'code_group' => 'PENGHASILAN',
                'code_value' => '300.000-500.000',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'com_cd' => 'PENGHASILAN_4',
                'code_nm' => '500.000-1.000.000',
                'code_group' => 'PENGHASILAN',
                'code_value' => '500.000-1.000.000',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'com_cd' => 'PENGHASILAN_5',
                'code_nm' => '1.000.000-2.000.000',
                'code_group' => 'PENGHASILAN',
                'code_value' => '1.000.000-2.000.000',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'com_cd' => 'PENGHASILAN_6',
                'code_nm' => '2.000.000-5.000.000',
                'code_group' => 'PENGHASILAN',
                'code_value' => '2.000.000-5.000.000',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'com_cd' => 'PENGHASILAN_7',
                'code_nm' => '>5.000.000',
                'code_group' => 'PENGHASILAN',
                'code_value' => '>5.000.000',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'com_cd' => 'SEMBAKO_1',
                'code_nm' => 'Telur',
                'code_group' => 'SEMBAKO',
                'code_value' => 'Telur',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'com_cd' => 'SEMBAKO_2',
                'code_nm' => 'Minyak',
                'code_group' => 'SEMBAKO',
                'code_value' => 'Minyak',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'com_cd' => 'SEMBAKO_3',
                'code_nm' => 'Gula',
                'code_group' => 'SEMBAKO',
                'code_value' => 'Gula',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'com_cd' => 'SEMBAKO_4',
                'code_nm' => 'Beras',
                'code_group' => 'SEMBAKO',
                'code_value' => 'Beras',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'com_cd' => 'SEMBAKO_5',
            'code_nm' => 'Makanan Sachet (Bubur, Mie)',
                'code_group' => 'SEMBAKO',
            'code_value' => 'Makanan Sachet (Bubur, Mie)',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'com_cd' => 'SEMBAKO_6',
                'code_nm' => 'Minuman Sachet',
                'code_group' => 'SEMBAKO',
                'code_value' => 'Minuman Sachet',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'com_cd' => 'SEMBAKO_7',
                'code_nm' => 'Bumbu penyedap',
                'code_group' => 'SEMBAKO',
                'code_value' => 'Bumbu penyedap',
                'tipe' => 'checkbox',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'com_cd' => 'SEMBAKO_8',
                'code_nm' => 'Lainnya',
                'code_group' => 'SEMBAKO',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'com_cd' => 'SKALA_KEMANFAATAN_1',
                'code_nm' => 'Tidak Bermanfaat sama sekali',
                'code_group' => 'SKALA_KEMANFAATAN',
                'code_value' => 'Tidak Bermanfaat sama sekali',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'com_cd' => 'SKALA_KEMANFAATAN_2',
                'code_nm' => 'Tidak Terlalu bermanfaat',
                'code_group' => 'SKALA_KEMANFAATAN',
                'code_value' => 'Tidak Terlalu bermanfaat',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'com_cd' => 'SKALA_KEMANFAATAN_3',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'SKALA_KEMANFAATAN',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'com_cd' => 'SKALA_KEMANFAATAN_4',
                'code_nm' => 'Cukup Bermanfaat',
                'code_group' => 'SKALA_KEMANFAATAN',
                'code_value' => 'Cukup Bermanfaat',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'com_cd' => 'SKALA_KEMANFAATAN_5',
                'code_nm' => 'Sangat Bermanfaat',
                'code_group' => 'SKALA_KEMANFAATAN',
                'code_value' => 'Sangat Bermanfaat',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'com_cd' => 'SKALA_KESEHARIAN_1',
                'code_nm' => 'Tidak terpengaruh Sama Sekali',
                'code_group' => 'SKALA_KESEHARIAN',
                'code_value' => 'Tidak terpengaruh Sama Sekali',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'com_cd' => 'SKALA_KESEHARIAN_2',
                'code_nm' => 'Tidak Terlalu terpengaruh',
                'code_group' => 'SKALA_KESEHARIAN',
                'code_value' => 'Tidak Terlalu terpengaruh',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'com_cd' => 'SKALA_KESEHARIAN_3',
                'code_nm' => 'Cukup terpengaruh',
                'code_group' => 'SKALA_KESEHARIAN',
                'code_value' => 'Cukup terpengaruh',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'com_cd' => 'SKALA_KESEHARIAN_4',
                'code_nm' => 'Terpengaruh',
                'code_group' => 'SKALA_KESEHARIAN',
                'code_value' => 'Terpengaruh',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'com_cd' => 'SKALA_KESEHARIAN_5',
                'code_nm' => 'Sangat terpengaruh',
                'code_group' => 'SKALA_KESEHARIAN',
                'code_value' => 'Sangat terpengaruh',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'com_cd' => 'SKALA_POSITIF_NEGATIF_1',
                'code_nm' => 'Sangat Negatif',
                'code_group' => 'SKALA_POSITIF_NEGATIF',
                'code_value' => 'Sangat Negatif',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'com_cd' => 'SKALA_POSITIF_NEGATIF_2',
                'code_nm' => 'Negatif',
                'code_group' => 'SKALA_POSITIF_NEGATIF',
                'code_value' => 'Negatif',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'com_cd' => 'SKALA_POSITIF_NEGATIF_3',
                'code_nm' => 'Netral',
                'code_group' => 'SKALA_POSITIF_NEGATIF',
                'code_value' => 'Netral',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'com_cd' => 'SKALA_POSITIF_NEGATIF_4',
                'code_nm' => 'Positif',
                'code_group' => 'SKALA_POSITIF_NEGATIF',
                'code_value' => 'Positif',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'com_cd' => 'SKALA_POSITIF_NEGATIF_5',
                'code_nm' => 'Sangat Positif',
                'code_group' => 'SKALA_POSITIF_NEGATIF',
                'code_value' => 'Sangat Positif',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'com_cd' => 'SKALA_SETUJU_TIDAKSETUJU_1',
                'code_nm' => 'Sangat Tidak Setuju',
                'code_group' => 'SKALA_SETUJU_TIDAKSETUJU',
                'code_value' => 'Sangat Tidak Setuju',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'com_cd' => 'SKALA_SETUJU_TIDAKSETUJU_2',
                'code_nm' => 'Tidak Setuju',
                'code_group' => 'SKALA_SETUJU_TIDAKSETUJU',
                'code_value' => 'Tidak Setuju',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'com_cd' => 'SKALA_SETUJU_TIDAKSETUJU_3',
                'code_nm' => 'Netral',
                'code_group' => 'SKALA_SETUJU_TIDAKSETUJU',
                'code_value' => 'Netral',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'com_cd' => 'SKALA_SETUJU_TIDAKSETUJU_4',
                'code_nm' => 'Setuju',
                'code_group' => 'SKALA_SETUJU_TIDAKSETUJU',
                'code_value' => 'Setuju',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'com_cd' => 'SKALA_SETUJU_TIDAKSETUJU_5',
                'code_nm' => 'Sangat Setuju',
                'code_group' => 'SKALA_SETUJU_TIDAKSETUJU',
                'code_value' => 'Sangat Setuju',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'com_cd' => 'SKALA_TERGANGGU_1',
                'code_nm' => 'Sangat Terganggu',
                'code_group' => 'SKALA_TERGANGGU',
                'code_value' => 'Sangat Terganggu',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'com_cd' => 'SKALA_TERGANGGU_2',
                'code_nm' => 'Cukup Terganggu',
                'code_group' => 'SKALA_TERGANGGU',
                'code_value' => 'Cukup Terganggu',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'com_cd' => 'SKALA_TERGANGGU_3',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'SKALA_TERGANGGU',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'com_cd' => 'SKALA_TERGANGGU_4',
                'code_nm' => 'Tidak Terlalu Terganggu',
                'code_group' => 'SKALA_TERGANGGU',
                'code_value' => 'Tidak Terlalu Terganggu',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'com_cd' => 'SKALA_TERGANGGU_5',
                'code_nm' => 'Tidak Peduli',
                'code_group' => 'SKALA_TERGANGGU',
                'code_value' => 'Tidak Peduli',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'com_cd' => 'SKALA_USAHA_1',
                'code_nm' => 'Tentu',
                'code_group' => 'SKALA_USAHA',
                'code_value' => 'Tentu',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'com_cd' => 'SKALA_USAHA_2',
                'code_nm' => 'Belum Semua',
                'code_group' => 'SKALA_USAHA',
                'code_value' => 'Belum Semua',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'com_cd' => 'SKALA_USAHA_3',
                'code_nm' => 'Sedang Berusaha',
                'code_group' => 'SKALA_USAHA',
                'code_value' => 'Sedang Berusaha',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'com_cd' => 'SKALA_USAHA_4',
                'code_nm' => 'Tidak Peduli',
                'code_group' => 'SKALA_USAHA',
                'code_value' => 'Tidak Peduli',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'com_cd' => 'SKALA_USAHA_5',
                'code_nm' => 'Tidak Menerapkan',
                'code_group' => 'SKALA_USAHA',
                'code_value' => 'Tidak Menerapkan',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'com_cd' => 'SUDAH_BELUM_1',
                'code_nm' => 'Sudah',
                'code_group' => 'SUDAH_BELUM',
                'code_value' => 'Sudah',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'com_cd' => 'SUDAH_BELUM_2',
                'code_nm' => 'Belum',
                'code_group' => 'SUDAH_BELUM',
                'code_value' => 'Belum',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'com_cd' => 'TIPE_1_REAKSI_1',
                'code_nm' => 'Tidak Peduli',
                'code_group' => 'TIPE_1_REAKSI',
                'code_value' => 'Tidak Peduli',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'com_cd' => 'TIPE_1_REAKSI_2',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'TIPE_1_REAKSI',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'com_cd' => 'TIPE_1_REAKSI_3',
                'code_nm' => 'Khawatir terhadap berita Hoaks-Profokatif-Konspirasi',
                'code_group' => 'TIPE_1_REAKSI',
                'code_value' => 'Khawatir terhadap berita Hoaks-Profokatif-Konspirasi',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'com_cd' => 'TIPE_1_REAKSI_4',
                'code_nm' => 'Tidak Khawatir karena dapat memilah informasi',
                'code_group' => 'TIPE_1_REAKSI',
                'code_value' => 'Tidak Khawatir karena dapat memilah informasi',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'com_cd' => 'TIPE_2_REAKSI_1',
                'code_nm' => 'Tidak Peduli',
                'code_group' => 'TIPE_2_REAKSI',
                'code_value' => 'Tidak Peduli',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'com_cd' => 'TIPE_2_REAKSI_2',
                'code_nm' => 'Biasa Saja',
                'code_group' => 'TIPE_2_REAKSI',
                'code_value' => 'Biasa Saja',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'com_cd' => 'TIPE_2_REAKSI_3',
                'code_nm' => 'Takut,Khawatir,Was Was',
                'code_group' => 'TIPE_2_REAKSI',
                'code_value' => 'Takut,Khawatir,Was Was',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'com_cd' => 'TIPE_2_REAKSI_4',
                'code_nm' => 'Waspada',
                'code_group' => 'TIPE_2_REAKSI',
                'code_value' => 'Waspada',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'com_cd' => 'TIPE_2_REAKSI_5',
                'code_nm' => 'Menerima Keadaan & Mengikuti Protokol Selanjutnya',
                'code_group' => 'TIPE_2_REAKSI',
                'code_value' => 'Menerima Keadaan & Mengikuti Protokol Selanjutnya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'com_cd' => 'TIPE_2_REAKSI_6',
                'code_nm' => 'Lainnya',
                'code_group' => 'TIPE_2_REAKSI',
                'code_value' => '',
                'tipe' => 'textarea',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'com_cd' => 'YA_TIDAK_1',
                'code_nm' => 'Ya',
                'code_group' => 'YA_TIDAK',
                'code_value' => 'Ya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'com_cd' => 'YA_TIDAK_2',
                'code_nm' => 'Tidak',
                'code_group' => 'YA_TIDAK',
                'code_value' => 'Tidak',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'com_cd' => 'YA_TIDAK_MUNGKIN_1',
                'code_nm' => 'Ya',
                'code_group' => 'YA_TIDAK_MUNGKIN',
                'code_value' => 'Ya',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'com_cd' => 'YA_TIDAK_MUNGKIN_2',
                'code_nm' => 'Tidak',
                'code_group' => 'YA_TIDAK_MUNGKIN',
                'code_value' => 'Tidak',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'com_cd' => 'YA_TIDAK_MUNGKIN_3',
                'code_nm' => 'Mungkin',
                'code_group' => 'YA_TIDAK_MUNGKIN',
                'code_value' => 'Mungkin',
                'tipe' => 'radio',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}