<?php

use Illuminate\Database\Seeder;

class PertanyaansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pertanyaans')->delete();
        
        \DB::table('pertanyaans')->insert(array (
            0 => 
            array (
                'id' => 1,
                'kategori' => 'Riwayat Kesehatan',
            'pertanyaan' => 'Dalam 14 hari terakhir, apakah ada demam (≥ 38oC) atau riwayat demam (≥ 38oC)?',
                'skor_ya' => 1,
                'skor_tidak' => 0,
                'deskripsi' => NULL,
                'tipe' => NULL,
                'grup' => NULL,
                'created_at' => '2020-02-06 07:56:53',
                'updated_at' => '2020-05-26 13:03:58',
            ),
            1 => 
            array (
                'id' => 2,
                'kategori' => 'Riwayat Kesehatan',
            'pertanyaan' => 'Dalam 14 hari terakhir, apakah mengalami gejala & tanda gangguan pernapasan (batuk, pilek, sakit tenggorokan, sesak napas)?',
                'skor_ya' => 1,
                'skor_tidak' => 0,
                'deskripsi' => NULL,
                'tipe' => NULL,
                'grup' => NULL,
                'created_at' => '2020-02-06 07:56:53',
                'updated_at' => '2020-05-26 13:04:13',
            ),
            2 => 
            array (
                'id' => 3,
                'kategori' => 'Riwayat Perjalanan',
            'pertanyaan' => 'Dalam 14 hari terakhir, apakah pernah kontak erat (kontak fisik atau berada dalam satu ruangan atau dalam radius 1 meter) dengan pasien positif COVID-19?',
                'skor_ya' => 1,
                'skor_tidak' => 0,
                'deskripsi' => NULL,
                'tipe' => NULL,
                'grup' => NULL,
                'created_at' => '2020-02-06 07:56:53',
                'updated_at' => '2020-05-26 13:04:28',
            ),
            3 => 
            array (
                'id' => 4,
                'kategori' => 'Riwayat Perjalanan',
            'pertanyaan' => 'Dalam 14 hari terakhir, apakah pernah berkunjung atau tinggal diluar negeri yang melakukan penularan lokal (zona merah)?',
                'skor_ya' => 1,
                'skor_tidak' => 0,
                'deskripsi' => NULL,
                'tipe' => NULL,
                'grup' => NULL,
                'created_at' => '2020-02-06 07:56:53',
                'updated_at' => '2020-05-26 13:04:42',
            ),
            4 => 
            array (
                'id' => 5,
                'kategori' => 'Riwayat Perjalanan',
            'pertanyaan' => 'Dalam 14 hari terakhir, apakah pernah berkunjung atau tinggal diarea penularan lokal di Indonesia (zona merah)?',
                'skor_ya' => 1,
                'skor_tidak' => 0,
                'deskripsi' => NULL,
                'tipe' => NULL,
                'grup' => NULL,
                'created_at' => '2020-02-06 07:56:53',
                'updated_at' => '2020-05-26 13:04:54',
            ),
            5 => 
            array (
                'id' => 6,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Apakah kegiatan keseharian anda terpengaruh sejak adanya Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_KESEHARIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Apakah pola kegiatan anda terpengaruh sejak adanya Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
            'deskripsi' => 'Contoh : (Sebelumnya bekerja di pagi hari, akibat covid-19 bekerja di malam hari)',
                'tipe' => 'radio',
                'grup' => 'SKALA_KESEHARIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'SEBELUM Pandemi Covid-19; Selain bekerja dan menuntut ilmu, kegiatan apa yang anda lakukan sehari-hari?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'KEGIATAN_SEHARI_HARI',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'SAAT Pandemi Covid-19; Selain bekerja dan menuntut ilmu, kegiatan apa yang anda lakukan sehari-hari?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'KEGIATAN_SEHARI_HARI',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Menurut anda, bagaimanakah perubahan terhadap keseharian akibat covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_POSITIF_NEGATIF',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Apakah interaksi keluarga terpengaruh akibat Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_KESEHARIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Menurut anda, bagaimana perubahan interaksi keluarga selama Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_POSITIF_NEGATIF',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Apakah anda merasa terganggu dengan adanya pembatasan kegiatan selama Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_TERGANGGU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Apakah anda telah menerapkan kebiasaan/protokol kesehatan pencegahan Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_USAHA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'kategori' => 'Keseharian',
                'pertanyaan' => 'Kebiaasaan apa yang sudah anda terapkan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'KEBIASAAN_DITERAPKAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'kategori' => 'Keseharian',
            'pertanyaan' => 'Apakah anda setuju dengan adanya pembatasan kegiatan (Social Distancing) selama Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_SETUJU_TIDAKSETUJU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'kategori' => 'Keseharian',
            'pertanyaan' => 'Apakah anda merasa pembatasan kegiatan (Social Distancing) selama Pandemi Covid-19 bermanfaat untuk kesehatan dan keselamatan masyarakat?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_KEMANFAATAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah Pekerjaan anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'JENIS_PEKERJAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah Pola/Jam Kerja anda terpengaruh oleh Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_KESEHARIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Bagaimana perubahan Pola/Jam Kerja akibat Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_POSITIF_NEGATIF',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Berapa Penghasilan anda dalam kurun waktu 1 bulan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'PENGHASILAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah penghasilan anda terdampak akibat pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'YA_TIDAK_MUNGKIN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Setelah Pandemi Covid-19, berapa Penghasilan anda daam kurun waktu 1 bulan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'PENGHASILAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah Pemenuhan Kebutuhan harian anda terganggu akibat perubahan penghasilan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_TERGANGGU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah anda memiliki pekerjaan lain/Alternatif selama Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'YA_TIDAK',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah Covid-19 Menghilangkan Pekerjaan anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'YA_TIDAK_MUNGKIN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Apakah Covid-19 membuat anda membutuhkan sumber penghasilan lain?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'YA_TIDAK_MUNGKIN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Menurut anda seberapa besar pengaruh Covid-19 terhadap ekonomi anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_KESEHARIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'kategori' => 'Ekonomi',
                'pertanyaan' => 'Bagaimanakah pengaruh tersebut?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_POSITIF_NEGATIF',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Bagaimana Pemahaman anda terkait Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'PEMAHAMAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Bagaimana Pemahaman anda terkait Pencegahan Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'PEMAHAMAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Menurut anda, bagaimana pengaruh Pandemi Covid-19 terhadap kondisi psikis/Mental anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_POSITIF_NEGATIF',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Menurut anda, bagaimana pengaruh Pandemi Covid-19 terhadap ketenangan hidup anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_POSITIF_NEGATIF',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah anda dapat menerima informasi terkait Covid-19 dengan Mudah?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'Melalui TV,Radio,Surat Kabar, Leaflet, Pemerintah, Internet, dsb',
                'tipe' => 'radio',
                'grup' => 'KEMUDAHAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Seberapa baik anda memilah informasi terkait Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'Apakah anda bisa membedakan informasi yang benar/salah, informatif/profokatif',
                'tipe' => 'radio',
                'grup' => 'KEMAMPUAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Bagaimana Reaksi anda terhadap banyaknya informasi terkait Covid-19 yang anda Terima?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'TIPE_1_REAKSI',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Setelah Melihat/mendengar informasi terkait Covid-19, Bagaimana Reaksi Anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'TIPE_2_REAKSI',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Bagaimana Pendapat anda terkait isu-isu konspirasi terkait Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'Isu/kabar tentang ‘dalang/penyebab’ covid-19, alasan mengapa covid-19 belum berakhir/terus tersebar, dll',
                'tipe' => 'radio',
                'grup' => 'KEPEDULIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Bagaimana Pendapat anda terkait berita-berita profokatif terkait Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'Rumor/isu untuk tidak berdekatan/Menjauhi  tenaga medis, rumor/isu untuk menjauhi seseorang dengan etnis china, dsb.',
                'tipe' => 'radio',
                'grup' => 'KEPEDULIAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Menurut anda, bagaimana pengaruh Covid-19 terhadap pola pikir anda dalam mengolah informasi?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'PENGARUH',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
            'pertanyaan' => 'Apakah anda setuju dengan adanya pembatasan kegiatan (Social Distancing) selama Pandemi Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_SETUJU_TIDAKSETUJU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah anda sudah menerapkan praktk Social Distancing?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SKALA_USAHA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apa yang anda rasakan setelah menerapkan praktik Social Distancing',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'TIPE_2_REAKSI',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah Anda Mempercayai Berita terkait Covid-19 yang anda terima dari TV/Radio?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'KEPERCAYAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah Anda Mempercayai Berita terkait Covid-19 yang anda terima dari Media Sosial/Internet?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'WA Group, Instagram, Facebook, dsb',
                'tipe' => 'radio',
                'grup' => 'KEPERCAYAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah Anda Mempercayai Berita terkait Covid-19 yang anda terima dari Pemerintah/Tenaga Medis/Satgas?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'Himbauan, Berita, Pengumuman, Kebijakan, dsb',
                'tipe' => 'radio',
                'grup' => 'KEPERCAYAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah Anda Mempercayai Berita terkait Covid-19 yang anda terima dari Keluarga/Teman/Tetangga?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'KEPERCAYAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'kategori' => 'Psikologi & Penerimanaan Informasi Masyarakat',
                'pertanyaan' => 'Apakah Anda Mempercayai Berita terkait Covid-19 yang anda terima dari kegiatan Sosialisasi/Edukasi?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => 'Baik dari instansi Pemerintah/Tenaga Medis/Akademisi/Organisasi Volunteer, dsb',
                'tipe' => 'radio',
                'grup' => 'KEPERCAYAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Sebelum Pandemi Covid-19, apakah anda bisa memenuhi kebutuhan Pokok anda dengan baik?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'KESEJAHTERAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Selama Pandemi Covid-19, apakah anda bisa memenuhi kebutuhan Pokok anda dengan Baik?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'KESEJAHTERAAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'kategori' => 'Kebutuhan',
            'pertanyaan' => 'Apakah anda merupakan warga yang mendapatkan program Bantuan? (Di luar bantuan Covid-19)',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'YA_TIDAK_MUNGKIN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'kategori' => 'Kebutuhan',
            'pertanyaan' => 'Apakah anda sudah pernah menerima bantuan (logistik, sembako, alat kesehatan) Covid-19?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'SUDAH_BELUM',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Dari Manakah Asal Bantuan Tersebut?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'ASAL_BANTUAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Apakah Bantuan tersebut cukup dalam memenuhi kebutuhan pokok harian anda?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'PEMENUHAN_KEBUTUHAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Apabila anda mendapatkan bantuan, bantuan apa saja yang anda butuhkan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'radio',
                'grup' => 'JENIS_BANTUAN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Apabila Menerima Bantuan Sembako, Bantuan apa yang paling anda Butuhkan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'SEMBAKO',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'kategori' => 'Kebutuhan',
                'pertanyaan' => 'Apabila Menerima Bantuan Logistik Medis, Bantuan apa yang paling anda Butuhkan?',
                'skor_ya' => 0,
                'skor_tidak' => 0,
                'deskripsi' => '',
                'tipe' => 'checkbox',
                'grup' => 'MEDIS',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}